### ISSUE TITLE
2fa Authentication

### ISSUE THREAD

**Issue by MikeAnderson-E16247** [CrossRealms/Splunk-App-Auto-Update-MaxMind-Database#24]
Is there any possibility of this app being updated to the new 2FA standards that Maxmind is starting to use? I'm not sure how it would be done, as the 2fa seems to require either email tokens or an auth app, but was wondering if this was in the roadmap
https://support.maxmind.com/hc/en-us/articles/1260803946470-Two-Factor-Authentication-2FA-?utm_campaign=Required%202FA&utm_medium=email&_hsmi=266010548&_hsenc=p2ANqtz-8GfGlBheMQo6QR6euwa7c2pLbkPwfxEDZsPqTk8gMJZaU7mEyqJEJ7w9mtWmzyv-kvkTpNruiCq7GktpvqNTsQeSj9ZQ&utm_content=266010548&utm_source=hs_email

**Comment by VatsalJagani** [comment]
@MikeAnderson-E16247 - I think 2FA does not apply to License Keys that what App uses.

**Comment by MikeAnderson-E16247** [comment]
Turns out the 2fa is for user accounts signing into the maxmind website, not for scripted downloads of the mmdb.
