### ISSUE TITLE
Database Update location and logging

### ISSUE THREAD

**Issue by pablo808** [CrossRealms/Splunk-App-Auto-Update-MaxMind-Database#31]
I installed the latest 3.1.0 version and ran an update manually which appears to have worked successfully but I am not able to confirm the database location.  

The Splunk log search (index=_internal  sourcetype="auto_update_maxmind_db") does not show any results either.

Where on the file system is the database and log file?

**Comment by mahirchavda** [comment]
Hi @pablo808, It gets written to the splunk_dir/etc/apps/search/lookups dir.

**Comment by pablo808** [comment]
Thank you.
