### ISSUE TITLE
Splunk Cloud compatibility in version 3.2.0

### ISSUE THREAD

**Issue by mflpopescu** [CrossRealms/Splunk-App-Auto-Update-MaxMind-Database#37]
What happened, has version 3.2.0 lost the Splunk Cloud compatibility?

<img width="1389" alt="image" src="https://github.com/CrossRealms/Splunk-App-Auto-Update-MaxMind-Database/assets/22353083/bde53a94-267c-467d-9d48-8a8206f47bfb">

**Comment by VatsalJagani** [comment]
Sometimes it takes some time to get that. But I see no problem with compatibility now.

<img width="1144" alt="image" src="https://github.com/CrossRealms/Splunk-App-Auto-Update-MaxMind-Database/assets/20964366/96318c8b-5724-4c7e-9265-ccc0d01cebd3">
