### ISSUE TITLE
Upgrade to 3.2.0 in Splunk Cloud, update is broken in 2 seperate cloud stacks

### ISSUE THREAD

**Issue by dave-safian-kyndryl** [CrossRealms/Splunk-App-Auto-Update-MaxMind-Database#38]
We get the error: Error in 'maxminddbupdate' command: External search command exited unexpectedly with non-zero error code 1.

I'm not seeing any useful logs as a result of the update failure.

The creds work fine on an older version of the app on a third splunk cloud stack.

**Comment by epic-david** [comment]
This is due to a syntax error on this line: https://github.com/CrossRealms/Splunk-App-Auto-Update-MaxMind-Database/blob/master/bin/mmdb_utils.py#L302

I created a PR with the fix: https://github.com/CrossRealms/Splunk-App-Auto-Update-MaxMind-Database/pull/39

**Comment by JRJ13** [comment]
Is there an ETA for this update? I installed the 3.2.0 app in my Splunk Cloud environment and have been getting the "Error in 'maxminddbupdate' command: External search command exited unexpectedly with non-zero error code" since it was installed about a month ago.

**Comment by VatsalJagani** [comment]
We have just released the new version of v4.0.0 on Splunkbase.

https://splunkbase.splunk.com/app/5482

See the release notes and other documentation here - https://github.com/CrossRealms/Splunk-App-Auto-Update-MaxMind-Database

**Comment by JRJ13** [comment]
Vatsal,

Thank you very much for the update. I am using Splunk Cloud and currently
running version 3.2.0 but there is no option to upgrade. Would I need to
uninstall 3.2.0 and then install ver. 4.0.0?
