### ISSUE TITLE
Version 4.0.0 Splunk Cloud compatibility

### ISSUE THREAD

**Issue by JRJ13** [CrossRealms/Splunk-App-Auto-Update-MaxMind-Database#47]
Will this new version eventually be made compatible with Splunk Cloud?

**Comment by VatsalJagani** [comment]
Yes, it will when first cloud customer request installation with Cloud support. Or in next few days.

**Comment by rsrak395** [comment]
How we can get this for Splunk cloud as it is need for our encvironment. Could you please help with the process

**Comment by rsrak395** [comment]
It is now available for SPlunk cloud but when I am trying to configure it, without providing Proxy we are getting error as "Unable to save the Max Mind database configuration. Data is not in proper format. 'mmdb_config_proxy_url'".

Could you please help with this error. @VatsalJagani

**Comment by VatsalJagani** [comment]
@rsrak395 - Somehow I don't see that error. Will you be able to try uninstalling it, installing it again and try configuring it again??

And please share the logs from App afterwards if you still face the same issue.

**Comment by sumang99** [comment]
Does Auto Update MaxMind Database - version 4.0.0 is compatible with Python3 ? If so how can be update the app to use python3 instead of default python2.

**Comment by mahirchavda** [comment]
yes. It is compatible with python3
