### ISSUE TITLE
Proxy without authentication

### ISSUE THREAD

**Issue by Zzo911** [CrossRealms/Splunk-App-Auto-Update-MaxMind-Database#48]
Hello,

Our proxy does not use authentication, but while using it I have an error.
`ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))`

My proxy setting is:
`http://[proxy_fqdn]:[proxy_port]`

MaxMind app version 4.0.0

Regards

**Comment by hardikhdholariya** [comment]
Hi @Zzo911, Can you please test the proxy connection on the same machine to see the issue is on app side or connectivity side?

Run the following curl command on command prompt and provide the result:

curl --proxy "**<PROXY_URL>**" "https://www.google.com"
